---
title: "Tools für Educational Data Mining"
author: "Ramon Füglister"
date: "2024-09-23"
categories: [edm]
---

This is the first post in a Quarto blog. Welcome!

```{r}
# Laden der benötigten Bibliotheken
library(rvest)

# Login-Informationen
username <- "DEIN_BENUTZERNAME"
password <- "DEIN_PASSWORT"

# Ziel-URL des Logins
login_url <- "https://www.beispielwebsite.com/login"

# Erstellen des Sessions-Objekts und Abrufen der Login-Seite
session <- html_session(login_url)
login_page <- session %>% rvest::html_nodes("form") %>% .[[1]]

# Erstellen der Login-Daten
login_data <- list(
  o_fiooldap_login_name = username,
  o_fiooldap_login_pass = password
)

# Senden des Login-Requests
response <- session %>% rvest::submit_form(login_page, login_data)

# Überprüfen, ob die Anmeldung erfolgreich war
if (response$url == login_url) {
  stop("Anmeldung fehlgeschlagen")
} else {
  # Hier kannst du den Code für die Datenextraktion oder das Scraping einfügen
}

```

```{r}
#| label: scatterplot

ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_minimal()
```